### PR TITLE
Run tests without user input

### PR DESCRIPTION
**Pull request by nottrobin**
As explained here:
https://github.com/facebookincubator/create-react-app/issues/1137#issuecomment-269934190

QA
--

``` bash
npm install
npm run test
```

See that tests run (and fail) without needing to prompt the user.

### CODE REVIEW

**Review by barrymcgee — CHANGES_REQUESTED** [review]
Can you please add an alias to replicate the original test with watcher behaviour? Maybe `npm run test-watch` or similar? You'll also need to update the README.

**Comment by nottrobin** [comment]
No, I won't do this as I don't know how. This isn't my testing library, I don't know fully all the ways we might want to run it and I don't have time right now to understand it.

As far as I'm concerned this PR is to fix #19 so it's mergeable, so that this project conforms with the standard interface for `npm run test`( or `yarn run test`) that every other project conforms to.

Either this PR can be merged as-is, or #19 can be unmerged. Further improvements should be done with future PRs - if you don't have time to do those follow-up PRs now, and instead feel like filing issues to track that future work, that would also be appreciated.

**Comment by nottrobin** [comment]
In fact, since test currently fail in `master`, #19 should probably be unmerged either way.

**Comment by nottrobin** [comment]
I've discovered that the "CI=true" is not actually necessary as it's [defined in Travis by default](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables), so the best solution is to leave this at the default.

This will work until we add the run script. At that point, we'll need to modify the run script to pass the `$CI¬ environment variable through to the running containers: [issue filed](https://github.com/canonical-webteam/generator-canonical-webteam/issues/46).

So for now I'm going to close this PR and add 2 new issues:

- [Make tests pass](https://github.com/vanilla-framework/vanilla-components/issues/24)
- [Add .travis.yaml file & enable CI](https://github.com/vanilla-framework/vanilla-components/issues/25)

**Pull request closed without merging**
